#!/usr/bin/env bash
# Create an iPXE boot disk that tries to connect to a series of servers to grab a signed
# kernel and, secondly, configuration files via an encrypted boot server
# (see https://github.com/SojournLabs/netboot/tree/master/boot_server).
#
# Usage:
#     TLS_KEY=path/to/key $0 imageserver1 templateserver1 imageserver2 templateserver2 ...
#
# Image servers contain signed kernels while template servers serve up configuration
# information.
#
# Assumes the environment variable VAPR_CERTSTORE is set to the directory containing
# certificates, including the root CA at ca.crt. These are set as part of vapr
# (https://github.com/SojournLabs/vapr), although you can set them manually.

if [[ "${TLS_KEY}" == "" ]]; then
    echo "No key file specified using environment variable TLS_KEY."
    exit 1
fi

KEY_FILE=$(cd $(dirname "${TLS_KEY}"); pwd)/$(basename "${TLS_KEY}")

docker run --rm -t -i \
    -v "${VAPR_CERTSTORE:=`pwd`/certstore}":/vapr/certstore:ro \
    -v "${KEY_FILE}":/vapr/keys/$(basename "${KEY_FILE}"):ro \
    -v "${VAPR_BUILDDIR:=`pwd`}":/vapr/build \
    sojournlabs/ipxe_builder "$@"