#!/usr/bin/env bash
# Default values
# Root certificate authority certificate location
VAPR_CAROOT=${VAPR_CAROOT:=config/cacert.pem}
# iPXE boot script location
VAPR_IPXE_BOOTSCRIPT=${VAPR_IPXE_BOOTSCRIPT:=config/bootscript.ipxe}
# Client certificate for client authentication (optional)
VAPR_CLIENT_CERT=${VAPR_CLIENT_CERT:=config/ipxeclient.crt}
# Client key for client authentication (optional)
VAPR_CLIENT_KEY=${VAPR_CLIENT_KEY:=config/ipxeclient.key}

###
if [ ! -f ${VAPR_CAROOT} ]; then
    echo "Unable to locate root certificate authority certificate file."
    exit 1
fi

if [ ! -f ${VAPR_IPXE_BOOTSCRIPT} ]; then
    echo "Unable to locate iPXE boot script."
    exit 1
fi

if ! mkdir tmp; then
    echo Unable to create temporary directory.
    exit 1
fi

cp ${VAPR_CAROOT} tmp
cp ${VAPR_IPXE_BOOTSCRIPT} tmp

# Set up client authentication.
if [[ -f ${VAPR_CLIENT_CERT} && -f ${VAPR_CLIENT_KEY} ]]; then
    cp ${VAPR_CLIENT_CERT} tmp/ipxeclient.crt
    cp ${VAPR_CLIENT_KEY} tmp/ipxeclient.key
    CLIENT_AUTH="CERT=/vapr/config/ipxeclient.crt PRIVKEY=/vapr/config/ipxeclient.key"
else
    tput bold; tput setaf 3
    printf "WARNING: "
    tput sgr0
    echo No client authentication enabled.
fi

VAPR_DATA_DIR_config=`pwd`/tmp VAPR_DATA_DIR_build=`pwd`/build/boot_images ./dockertools/bin/run ipxe_builder.docker ipxe_builder bash -c "make -C ipxe/src EMBED=/vapr/config/bootscript.ipxe TRUST=/vapr/config/cacert.pem ${CLIENT_AUTH}; for FILENAME in ipxe.iso ipxe.dsk ipxe.usb; do cp ipxe/src/bin/\$FILENAME build; done"
rm -Rf tmp
