#!/usr/bin/env bash
# Default values

# iPXE server location
if [ ! -f build/boot_server/bootserver ]; then
    VAPR_IPXE_SERVER=${VAPR_IPXE_SERVER:=/usr/bin/bootserver}
else
    VAPR_IPXE_SERVER=${VAPR_IPXE_SERVER:=build/boot_server/bootserver}
fi

if [ ! -d ipxe_server.config ]; then
    export VAPRDATA_DIRRO_server_root=${VAPRDATA_DIRRO_server_root:=$(cd ~core; pwd)/ipxe_server.config}
else
    export VAPRDATA_DIRRO_server_root=${VAPRDATA_DIRRO_server_root:=ipxe_server.config}
fi

export VAPR_DATA_DIRRO_server=$(cd $(dirname ${VAPR_IPXE_SERVER}); pwd)

###
if [ ! -f ${VAPR_IPXE_SERVER} ]; then
    echo "Unable to locate iPXE boot server."
    exit 1
fi

DOCKER_DAEMONIZE=TRUE DOCKER_FLAGS="--name boot_server" ./dockertools/bin/run boot_server.docker boot_server
